version: "3.7"
services:
  jwt-app:
    image: jwt-example
    container_name: jwt-example
    ports:
      - "8001:8080"
    networks:
      - containernetwork
    depends_on:
      - postgres
      - redis

  user-app:
    image: user-app
    container_name: user-app
    ports:
      - "8002:8080"
    networks:
      - containernetwork
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:5.0.6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - containernetwork

  postgres:
    image: postgres:12.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=postgres
    volumes:
      - /usr/local/var/postgres:/var/lib/postgresql/data
    networks:
      - containernetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 10
networks:
  containernetwork: