package main.java;

import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.*;
import java.security.interfaces.RSAPublicKey;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.Base64;

public class Encryption {

    public static byte[] readFileBytes(String filename) throws IOException
    {
        Path path = Paths.get(filename);
        return Files.readAllBytes(path);
    }

    public static PublicKey readPublicKey(String filename) throws IOException, NoSuchAlgorithmException, InvalidKeySpecException
    {
        X509EncodedKeySpec publicSpec = new X509EncodedKeySpec(readFileBytes(filename));
        KeyFactory keyFactory = KeyFactory.getInstance("RSA");
        return keyFactory.generatePublic(publicSpec);
    }

    public static PrivateKey readPrivateKey(String filename) throws IOException, NoSuchAlgorithmException, InvalidKeySpecException
    {
        PKCS8EncodedKeySpec keySpec = new PKCS8EncodedKeySpec(readFileBytes(filename));
        KeyFactory keyFactory = KeyFactory.getInstance("RSA");
        return keyFactory.generatePrivate(keySpec);
    }

    public static byte[] encrypt(PublicKey key, byte[] plaintext) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException, IllegalBlockSizeException, BadPaddingException
    {
        Cipher cipher = Cipher.getInstance("RSA/ECB/OAEPWithSHA1AndMGF1Padding");
        cipher.init(Cipher.ENCRYPT_MODE, key);
        return cipher.doFinal(plaintext);
    }

    public static byte[] decrypt(PrivateKey key, byte[] ciphertext) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException, IllegalBlockSizeException, BadPaddingException
    {
        Cipher cipher = Cipher.getInstance("RSA/ECB/OAEPWithSHA1AndMGF1Padding");
        cipher.init(Cipher.DECRYPT_MODE, key);
        return cipher.doFinal(ciphertext);
    }

    public static void main(String[] args)
    {
        try
        {
            PublicKey publicKey1 = readPublicKey("public.der");
            PrivateKey privateKey1 = readPrivateKey("private.der");

            byte[] message1 = "Encryption Using DER file".getBytes("UTF8");
            byte[] secret1 = Base64.getEncoder().encode(encrypt(publicKey1, message1));
            byte[] recovered_message1 = decrypt(privateKey1, Base64.getDecoder().decode(secret1));

            System.out.println(new String(secret1));
            System.out.println(new String(recovered_message1, "UTF8"));

            /**
             *  Using PEM Keypair generated by SSL
             *  1. openssl genrsa -out rsakey.pem 4096
             *  2. openssl rsa -pubout -in rsakey.pem -out public.pem
             *  3. openssl pkcs8 -topk8 -in rsakey.pem -inform pem -out private.pem -outform pem -nocrypt
             */

            String privateKeyContent = new String(readFileBytes("private.pem"));
            String publicKeyContent = new String(readFileBytes("public.pem"));

            privateKeyContent = privateKeyContent.replaceAll("\\n", "").replace("-----BEGIN PRIVATE KEY-----", "").replace("-----END PRIVATE KEY-----", "");
            publicKeyContent = publicKeyContent.replaceAll("\\n", "").replace("-----BEGIN PUBLIC KEY-----", "").replace("-----END PUBLIC KEY-----", "");;

            KeyFactory keyFactory = KeyFactory.getInstance("RSA");

            PKCS8EncodedKeySpec keySpecPKCS8 = new PKCS8EncodedKeySpec(Base64.getDecoder().decode(privateKeyContent));
            PrivateKey privateKey2 = keyFactory.generatePrivate(keySpecPKCS8);

            X509EncodedKeySpec keySpecX509 = new X509EncodedKeySpec(Base64.getDecoder().decode(publicKeyContent));
            RSAPublicKey publicKey2 = (RSAPublicKey) keyFactory.generatePublic(keySpecX509);

            byte[] message2 = "Encryption Using PEM file".getBytes("UTF8");
            byte[] secret2 = Base64.getEncoder().encode(encrypt(publicKey2, message2));
            byte[] recovered_message2 = decrypt(privateKey2, Base64.getDecoder().decode(secret2));

            System.out.println(new String(secret2));
            System.out.println(new String(recovered_message2, "UTF8"));

            /**
             *  Using Generated KeyPairGeneator
             */
            KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("RSA");
            keyPairGenerator.initialize(2048);
            KeyPair keyPair = keyPairGenerator.generateKeyPair();

            byte[] message3 = "Encryption Using Key Pair Generator".getBytes("UTF8");
            byte[] secret3 = Base64.getEncoder().encode(encrypt(keyPair.getPublic(), message3));
            byte[] recovered_message3 = decrypt(keyPair.getPrivate(), Base64.getDecoder().decode(secret3));
            System.out.println(new String(secret3));
            System.out.println(new String(recovered_message3, "UTF8"));
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }
}
