logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG
spring:
  cloud:
    gateway:
      routes:
        - id: catch-all
          uri: no://op
          predicates:
            - Path=/**