logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG
liquibase:
  change-log: classpath:liquibase-changeLog.xml
  default-schema: gateway
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gateway
    password: password
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
#  cloud:
#    gateway:
#      routes:
#        - id: catch-all
#          uri: no://op
#          predicates:
#            - Path=/**