spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    password: password
    username: root
  jpa:
    database-platform: com.mysql.jdbc.Driver
#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/postgres
#    name: postgres
#    password: password
#    username: postgres
debug: true
