spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:password@localhost:5432/postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true